/// <reference types="pixi.js-legacy" />
declare module '@pixi/core' {
    export {
        AbstractBatchRenderer,
        AbstractRenderer,
        Attribute,
        autoDetectRenderer,
        BaseRenderTexture,
        BaseTexture,
        BatchDrawCall,
        BatchGeometry,
        BatchPluginFactory,
        BatchShaderGenerator,
        BatchTextureArray,
        Buffer,
        defaultFilterVertex,
        defaultVertex,
        Filter,
        Framebuffer,
        Geometry,
        GLProgram,
        GLTexture,
        MaskData,
        ObjectRenderer,
        Program,
        Quad,
        QuadUv,
        Renderer,
        RenderTexture,
        RenderTexturePool,
        resources,
        Shader,
        SpriteMaskFilter,
        State,
        System,
        systems,
        Texture,
        TextureMatrix,
        TextureUvs,
        UniformGroup,
        ViewableBuffer,
    } from 'pixi.js-legacy';
}
